FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*
    
# Copy your custom config and web page
#COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /var/www/html/

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]