version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      # for bind mount and easy development
      - ./frontend:/var/www/html
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M


  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    # port exposed for debugging
    # ports:
    #   - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:13.22-alpine3.22
    # port exposed for debugging
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}